### ISSUE TITLE
Problem with building dynamic menu

### ISSUE THREAD

**Issue by christophmerscher** [jnvsor/jekyll-dynamic-menu#2]
Hi Jonathan,

i have a problem when i try to generate the menu dynamically.  My directory structure looks like:
- Home (/)
- Intro (/intro/)
  *\* Welcome(/intro/welcome/)
  *\* Vision(/intro/vision/)
  *\* Process(/intro/process/)
- Other (/other/)

In each directory is a index.md file (without permalink).
The menu is build dynamically without any problems but when i click on a leaf in the submenu of intro (Welcome, Vision or Process) the branch (Intro) will be closed. 
Oddly one leaf behaves correctly (when i clicked on the leaf the branch (Intro) is not closed)  normaly for the first subfolder who was created.

Thanks for your help.

Christoph

**Comment by jnvsor** [comment]
I can't reproduce this even with a fresh jekyll install.. Can you zip your site and send it to me?

**Comment by christophmerscher** [comment]
https://github.com/christophmerscher/christophmerscher.github.io

**Comment by christophmerscher** [comment]
its a tar

**Comment by jnvsor** [comment]
I think you replied to the github issue not to me, can I assume that repo link is the site in question?

If so you're using an old or modified version of automenu and it works fine with the latest one: https://github.com/jnvsor/jekyll-dynamic-menu/blob/master/_includes/automenu
