### ISSUE TITLE
Doesnt work with sub menus

### ISSUE THREAD

**Issue by Kurren123** [jnvsor/jekyll-dynamic-menu#3]
Hi

Automenu doesnt work with the current version of jekyll `~>3.5`. It outputs the top level menu items but is not recursive.

**Comment by jnvsor** [comment]
Thanks I'll take a look when I have a bit

**Comment by jnvsor** [comment]
Sorry it's been a while - I just tried it out with 3.5.2 and it works fine for me. Do you have a repo to reproduce it with?
