### ISSUE TITLE
Different page location

### ISSUE THREAD

**Issue by CannonballSkippy** [jnvsor/jekyll-dynamic-menu#4]
This might be a dumb question but I have all my pages in a folder called _docs, (which is actually a collection). How can I change the code to get page files from the directory _docs instead?

**Comment by jnvsor** [comment]
I presume you're using automenu? If you change the assignment on [line 4](https://github.com/jnvsor/jekyll-dynamic-menu/blob/master/_src/automenu#L4) to `site.docs` and [rebuild](https://github.com/jnvsor/jekyll-dynamic-menu/blob/master/build.sh) it should work.
